name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  get-subfolders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Subfolders
        id: set-matrix
        run: |
          subfolders=$(find . -mindepth 2 -name 'Cargo.toml' -exec dirname {} \; | python3 -c 'import sys, json; print(json.dumps([line.strip() for line in sys.stdin]))')
          echo "::set-output name=matrix::{\"project\": $subfolders}"

  build_and_test:
    needs: get-subfolders
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-subfolders.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract warnings and create issues
        working-directory: ${{ matrix.project }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cargo clippy --verbose 2>&1 | grep '^warning:' | python3 $GITHUB_WORKSPACE/.github/scripts/create_issues.py

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo build --verbose

      - name: Test ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo test --verbose
