name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(steps.get-subfolders.outputs.subfolders) }}

    steps:
      - name: Get Subfolders
        id: get-subfolders
        run: |
          subfolders=$(find . -mindepth 2 -name 'Cargo.toml' -exec dirname {} \; | python3 -c 'import sys, json; print(json.dumps([line.strip() for line in sys.stdin]))')
          echo "subfolders=$subfolders" >> $GITHUB_ENV
          echo "::set-output name=subfolders::$subfolders"

      - uses: actions/checkout@v3

      - name: Build and run tests for ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo clippy --verbose
          cargo build --verbose
          cargo test --verbose
