name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  get-subfolders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Subfolders
        id: set-matrix
        run: |
          subfolders=$(find . -mindepth 2 -name 'Cargo.toml' -exec dirname {} \; | python3 -c 'import sys, json; print(json.dumps([line.strip() for line in sys.stdin]))')
          echo "matrix={\"project\": $subfolders}" >> $GITHUB_ENV

  analyse:
    needs: get-subfolders
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-subfolders.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Analyse ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo clippy --verbose

  build:
    needs: analyse
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-subfolders.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-subfolders.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Test ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo test --verbose
