name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ steps.set-matrix.outputs.subfolders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Subfolders
        id: set-matrix
        run: |
          subfolders=$(find . -mindepth 2 -name 'Cargo.toml' -exec dirname {} \; | python3 -c 'import sys, json; print(json.dumps([line.strip() for line in sys.stdin]))')
          echo "::set-output name=subfolders::${subfolders}"

      - name: Build ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo build --verbose

      - name: Test ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: |
          cargo test --verbose
